# Generated by Django 4.1.7 on 2023-02-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.CharField(default='No URL Provided', max_length=200, null=True),
        ),
    ]
